### ISSUE TITLE
Undefined Functions

### ISSUE THREAD

**Issue by MumuSec** [q231950/xingapi#2]
Hey,
great Wrapper!

But I got the following errors:

```
..\..\q231950\xingapi\consumercredentials.go:8: undefined: ConsumerCredentia
..\..\q231950\xingapi\consumercredentials.go:9: undefined: ConsumerCredentia
..\..\q231950\xingapi\oauthauthenticator.go:66: undefined: NewCredentials
```

consumercredentials:

``` go
package xingapi

type ConsumerCredentialsExample struct {
    Token string
    Secret string
}

func NewCredentialsExample() ConsumerCredentials {
    return ConsumerCredentials{"xxx", "xxx"}
}
```

Have you an idea?

**Comment by MumuSec** [comment]
I think I fixed with renaming the Function.

**Comment by q231950** [comment]
Hello MuhPirat, as you can see in the .gitignore https://github.com/q231950/xingapi/blob/master/.gitignore#L28 the `ConsumerCredentials.go` file is being ignored. As described in the readme the user of the xingapi client is supposed to copy `ConsumerCredentialsExample.go` to `ConsumerCredentials.go` since your sensitive XING token/secret will be stated there. As it is being ignored by the git you are on the safe side in case you push any changes to a possibly public remote.
